# Generated by Django 5.2.5 on 2025-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Unique identifier for the song to e.g. access it via API.', unique=True, verbose_name='Slug')),
                ('file', models.FileField(upload_to='carillon/songs/', verbose_name='MIDI file')),
                ('transpose', models.IntegerField(default=0, help_text='Transposition in semitones, e.g. -12 for one octave down.', verbose_name='Transpose')),
                ('tempo', models.PositiveSmallIntegerField(blank=True, help_text='The tempo of the song in beats per minute (BPM). If not set, the tempo is taken from the MIDI file.', null=True, verbose_name='Tempo')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
