# Generated by Django 5.2.5 on 2025-10-08 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carillon',
            name='volume',
            field=models.PositiveSmallIntegerField(default=127, help_text='The volume of the carillon (0-127).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)], verbose_name='Volume'),
        ),
    ]
