# Generated by Django 5.2.5 on 2025-08-18 10:01

import carillon.models.rule
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='The priority of the rule. Higher values means firstly evaluated.', verbose_name='Priority')),
                ('cancel_following', models.BooleanField(default=False, help_text='If checked, no following rule with smaller priority will be executed if this rule applies.', verbose_name='Cancel following rules')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='A JSON object actually defining the condition.', validators=[carillon.models.rule.validate_rule_condition], verbose_name='Condition')),
                ('song', models.ForeignKey(blank=True, help_text='The song to play when the rule applies.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='carillon.song', verbose_name='Song')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['priority'],
            },
        ),
    ]
