# Generated by Django 5.2.5 on 2025-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carillon',
            name='default',
            field=models.BooleanField(default=False, help_text='Whether this carillon is the default carillon. Only one carillon can be the default. If activated here, another carillon that was the default will loose that status.', verbose_name='Default'),
        ),
    ]
