# Generated by Django 5.2.5 on 2025-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0002_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='repeat',
            field=models.CharField(choices=[('o', 'Off'), ('h12', 'For every hour once 12-based'), ('h24', 'For every hour once 24-based'), ('m15', 'For every 15 minutes'), ('m30', 'For every 30 minutes')], default='o', help_text='How often the played song should be repeated if the rule applies.', max_length=3, verbose_name='Repeat'),
        ),
    ]
