# Generated by Django 5.2.7 on 2025-10-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0002_carillon_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-priority'], 'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='The priority of the rule. Higher values means firstly evaluated.', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='striker',
            name='carillon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strikers', to='carillon.carillon', verbose_name='Carillon'),
        ),
    ]
