# Generated by Django 5.2.5 on 2025-08-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0003_rule_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tempo',
        ),
        migrations.AddField(
            model_name='song',
            name='tempo_multiplier',
            field=models.FloatField(default=1.0, help_text='A multiplier for the tempo of the song. This can be used to speed up or slow down the song.', verbose_name='Tempo Multiplier'),
        ),
    ]
