# Generated by Django 5.2.5 on 2025-08-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0003_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carillon',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this carillon is active and can be used. May be deactivated to mute all songs.', verbose_name='Active'),
        ),
    ]
