# Generated by Django 5.2.5 on 2025-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0004_remove_song_tempo_song_tempo_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('port_name', models.CharField(blank=True, default='', help_text='The name of the serial port used to connect to the carillon.', max_length=255, verbose_name='Port Name')),
            ],
        ),
    ]
