# Generated by Django 5.2.5 on 2025-08-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0005_carillon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carillon',
            options={'verbose_name': 'Carillon', 'verbose_name_plural': 'Carillons'},
        ),
    ]
