# Generated by Django 5.2.5 on 2025-08-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0006_alter_carillon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Striker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('carillon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strikers', to='carillon.carillon', verbose_name='Carillon')),
            ],
            options={
                'verbose_name': 'Striker',
                'verbose_name_plural': 'Strikers',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='striker',
            field=models.ForeignKey(default='', help_text='The striker that checks, if the rule applies.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='carillon.striker', verbose_name='Striker'),
        ),
    ]
