# Generated by Django 5.2.5 on 2025-08-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0007_striker_rule_striker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='striker',
            field=models.ForeignKey(help_text='The striker that checks, if the rule applies.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='carillon.striker', verbose_name='Striker'),
        ),
    ]
