# Generated by Django 5.2.5 on 2025-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0008_alter_rule_striker'),
    ]

    operations = [
        migrations.AddField(
            model_name='striker',
            name='priority',
            field=models.IntegerField(default=0, help_text="The priority of this striker, used to determine if it should abort other strikers' songs.", verbose_name='Priority'),
        ),
    ]
