# Generated by Django 5.2.5 on 2025-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0009_striker_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='striker',
            name='check_type',
            field=models.CharField(choices=[('M', 'Check manually, no automatic checks'), ('m', 'Check every minute'), ('q', 'Check every quarter hour'), ('h', 'Check every half hour'), ('H', 'Check every hour')], default='M', help_text='The type of check condition or interval.', max_length=1, verbose_name='Check type'),
        ),
    ]
