# Generated by Django 5.2.5 on 2025-09-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carillon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('pin', models.CharField(blank=True, default='', max_length=10, verbose_name='I/O-Pin')),
                ('behaviour', models.CharField(choices=[('0', 'Disabled'), ('L', 'On input state low'), ('H', 'On input state high'), ('C', 'On change of input state')], default='0', help_text='Which trigger should call the striker?', max_length=1, verbose_name='Behaviour')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='carillon.striker', verbose_name='Striker')),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'ordering': ['pin'],
            },
        ),
    ]
