# Generated by Django 5.2.5 on 2025-09-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carillon', '0001_initial'),
        ('gpio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this input is active and should be monitored.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='input',
            name='error',
            field=models.CharField(blank=True, default='', help_text='An error message if there is an issue with this input. Will be cleared when the input is set active.', max_length=255, verbose_name='Error'),
        ),
        migrations.AddField(
            model_name='input',
            name='pull',
            field=models.CharField(choices=[('N', 'No pull resistor'), ('U', 'Pull-up resistor'), ('D', 'Pull-down resistor')], default='N', help_text='The internal pull resistor for the input pin.', max_length=1, verbose_name='Pull resistor'),
        ),
        migrations.AlterField(
            model_name='input',
            name='behaviour',
            field=models.CharField(choices=[('L', 'On input state low'), ('H', 'On input state high'), ('C', 'On change of input state')], default='C', help_text='Which trigger should call the striker?', max_length=1, verbose_name='Behaviour'),
        ),
        migrations.AlterField(
            model_name='input',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='carillon.striker', verbose_name='Striker'),
        ),
        migrations.AddConstraint(
            model_name='input',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), models.Q(('pin', ''), _negated=True)), fields=('pin',), name='unique_active_pin'),
        ),
    ]
