# Generated by Django 5.2.5 on 2025-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0002_input_active_input_error_input_pull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='deadtime',
            field=models.PositiveIntegerField(default=0, help_text='Time after a trigger during which no new triggers will be accepted.', verbose_name='Deadtime (ms)'),
        ),
        migrations.AddField(
            model_name='input',
            name='debounce',
            field=models.BooleanField(default=True, help_text='Whether to apply debouncing to the input signal.', verbose_name='Debounce'),
        ),
    ]
