---
name: pre-commit checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install Python-Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development]
      - name: Run Tests
        run: |
          SKIP=django-test pre-commit run --all-files
